### ISSUE TITLE
Document sample of images

### ISSUE THREAD

**Issue by peterdesmet** [Datafable/gbif-dataset-metrics#59]
At: https://github.com/peterdesmet/gbif-challenge/blob/master/documentation/images.md
- [x] Title
- [x] Description
- [x] Screenshot
- [x] Rationale
- [x] Services used
- [x] Suggestions for further development
- [x] Suggestions for GBIF

**Comment by peterdesmet** [comment]
Structure document at https://github.com/Datafable/gbif-dataset-metrics/blob/master/documentation/sample-of-images.md, is referenced in README

**Comment by peterdesmet** [comment]
@bartaelterman @niconoe, in the [documentation of the multimedia bar](https://github.com/Datafable/gbif-dataset-metrics/blob/master/documentation/multimedia-bar.md), I see `associatedMedia` is checked as well as the multimedia extension. Is this also the case for the sample of images?

In what order are images considered? Are only stillImages included?

**Comment by bartaelterman** [comment]
Aggregator updated. Only stillimages are included. @niconoe will probably be able to answer the question about the multimedia extension.

**Comment by niconoe** [comment]
We only extract data from the multimedia extension. 

But from your documentation of the multimedia bar, it seems one understanding/possibility would be that GBIF creates multimedia extensions for records that initially only have `associatedMedia`. That's indeed possible, but I don't have any evidence for that. Do you remember what you had in my mind when you wrote ` This functionality makes use of the multimedia extension in GBIF downloads, which contains all related multimedia, even those originally provided in associatedMedia`? 

Otherwise, we can try to confirm (or negate) this claim by either looking for corresponding data in the portal, either by asking to some people at GBIF. What do you think?

**Comment by peterdesmet** [comment]
No, it's probably true what I wrote originally. GBIF downloads standardize all multimedia to one extension. Those coming from `associatedMedia` will receive no type. We will thus ignore those with our filter on `stillImages` only, which is for the best, as `associatedMedia` is often not populated with good URLs.

**Comment by peterdesmet** [comment]
Also, good of my past self to document this, so that my present self can forget all this info. :smile_cat:

**Comment by peterdesmet** [comment]
Blocking #85

**Comment by peterdesmet** [comment]
Blocking #89

**Comment by peterdesmet** [comment]
Reviewed and edited in b79da054c062146b9dc82215747435c1f6e19c13
